POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de JavaScript",
  "description": "Descrição do curso de JavaScript"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses?search=react

###

GET http://localhost:3333/courses?orderBy=id

###

GET http://localhost:3333/courses/[ID]

###


PATCH http://localhost:3333/courses/[ID]
Content-Type: application/json
  
{
  "title": "Curso de Node.js",
  "description": "Descrição atualizada do curso de Node.js"
}

###

DELETE http://localhost:3333/courses/[ID]

###
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "joao.silva@gmail.com.teste",
  "password": "12345aA@"
}
