POST http://localhost:3333/courses
Content-Type: application/json
Authorization: [TOKEN]

{
  "title": "Implementando JWT na API",
  "description": "Descrição do curso de JWT"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses?search=react

###

GET http://localhost:3333/courses?orderBy=id

###

GET http://localhost:3333/courses/[ID]

###


PATCH http://localhost:3333/courses/[ID]
Content-Type: application/json
  
{
  "title": "Curso de Node.js",
  "description": "Descrição atualizada do curso de Node.js"
}

###

DELETE http://localhost:3333/courses/[ID]

###
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "exemple@exemple.com",
  "password": "12345aA@"
}

###
GET http://localhost:3333/courses/[ID]
Authorization: [TOKEN]
