POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Node.js"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/[ID]

###


PATCH http://localhost:3333/courses/[ID]
Content-Type: application/json
  
{
  "title": "Curso de Node.js",
  "description": "Descrição atualizada do curso de Node.js"
}

###

DELETE http://localhost:3333/courses/[ID]